export const api = "https://jsonplaceholder.typicode.com/users";

export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_EXPIRED = "LOGIN_EXPIRED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGOUT = "LOGOUT";
export const LOADINSPECTIONS = "LOADINSPECTIONS";
export const CLEARERROR = "CLEARERROR";
export const LOADING = "LOADING";
export const REGISTERED = "REGISTERED";
export const CREATION_SUCCESS = "CREATION_SUCCESS";
export const CREATION_FAILED = "CREATION_FAILED";
export const ISLOADING = "ISLOADING";
export const LOADINGFAILED = "LOADINGFAILED";
export const LOADINSPECTION = "LOADINSPECTION";

export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS';
export const PRODUCT_LOAD_FAILURE = 'PRODUCT_LOAD_FAILURE';

export const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
export const CATEGORY_LOAD_FAILURE = 'CATEGORY_LOAD_FAILURE';

export const PRODUCT_INSERT_FAILURE = 'PRODUCT_INSERT_FAILURE';
export const PRODUCT_INSERT_SUCCESS = 'PRODUCT_INSERT_SUCCESS';

export const CATEGORY_INSERT_FAILURE = 'CATEGORY_INSERT_FAILURE';
export const CATEGORY_INSERT_SUCCESS = 'CATEGORY_INSERT_SUCCESS';

export const FAMILY_LOAD_SUCCESS = 'FAMILY_LOAD_SUCCESS';
export const FAMILY_LOAD_FAILURE = 'FAMILY_LOAD_FAILURE';

export const FAMILY_INSERT_FAILURE = 'FAMILY_INSERT_FAILURE';
export const FAMILY_INSERT_SUCCESS = 'FAMILY_INSERT_SUCCESS';

export const TYPE_LOAD_SUCCESS = 'TYPE_LOAD_SUCCESS';
export const TYPE_LOAD_FAILURE = 'TYPE_LOAD_FAILURE';

export const TYPE_INSERT_FAILURE = 'TYPE_INSERT_FAILURE';
export const TYPE_INSERT_SUCCESS = 'TYPE_INSERT_SUCCESS';

export const CLIENT_INSERT_FAILURE = 'CLIENT_INSERT_FAILURE'
export const CLIENT_INSERT_SUCCESS = 'CLIENT_INSERT_SUCCESS'

export const CLIENT_LOAD_FAILURE = 'CLIENT_LOAD_FAILURE';
export const CLIENT_LOAD_SUCCESS = 'CLIENT_LOAD_SUCCESS';

export const ORIGIN_LOAD_FAILURE = 'ORIGIN_LOAD_FAILURE';
export const ORIGIN_LOAD_SUCCESS = 'ORIGIN_LOAD_SUCCESS';

export const ORIGIN_INSERT_FAILURE = 'ORIGIN_INSERT_FAILURE';
export const ORIGIN_INSERT_SUCCESS = 'ORIGIN_INSERT_SUCCESS';

export const VESSEL_LOAD_FAILURE = 'VESSEL_LOAD_FAILURE';
export const VESSEL_LOAD_SUCCESS = 'VESSEL_LOAD_SUCCESS';

export const VESSEL_INSERT_FAILURE = 'VESSEL_INSERT_FAILURE';
export const VESSEL_INSERT_SUCCESS = 'VESSEL_INSERT_SUCCESS';


export const PORT_LOAD_FAILURE = 'PORT_LOAD_FAILURE';
export const PORT_LOAD_SUCCESS = 'PORT_LOAD_SUCCESS';

export const PORT_INSERT_FAILURE = 'PORT_INSERT_FAILURE';
export const PORT_INSERT_SUCCESS = 'PORT_INSERT_SUCCESS';

export const USERS_WAITING_LOAD_FAILURE = 'USERS_WAITING_LOAD_FAILURE';
export const USERS_WAITING_LOAD_SUCCESS = 'USERS_WAITING_LOAD_SUCCESS';

export const USERS_WAITING_PATCH_FAILURE = 'USERS_WAITING_PATCH_FAILURE';
export const USERS_WAITING_PATCH_SUCCESS = 'USERS_WAITING_PATCH_SUCCESS';

export const USERS_LOAD_FAILURE = 'USERS_LOAD_FAILURE';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';


export const USERS_UPDATE_FAILURE = 'USERS_UPDATE_FAILURE';
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS';